module.exports = {
  AddReactions: "Добавлять реакции",
  Administrator: "Администратор",
  AttachFiles: "Приложить файлы",
  BanMembers: "Забанить пользователей",
  ChangeNickname: "Изменить никнейм",
  Connect: "Подключится",
  CreateInstantInvite: "Создавать моментальное приглошение",
  CreatePrivateThreads: "Создавать приватные ветки",
  CreatePublicThreads: "Создавать публичные ветки",
  DeafenMembers: "Заглушать пользователя",
  EmbedLinks: "Встраивать ссылки",
  KickMembers: "Кикнуть пользователей",
  ManageChannels: "Управлять каналами",
  ManageEmojisAndStickers: "Управлять емодзи и стикерами",
  ManageEvents: "Управлять Ивентами",
  ManageGuild: "Управление Сервером",
  ManageMessages: "Управление Сообщениями",
  ManageNicknames: "Управление никами",
  ManageRoles: "Управление ролями",
  ManageThreads: "Управление ветками",
  ManageWebhooks: "Управление вебхуками",
  MentionEveryone: "Упомянуть всех",
  ModerateMembers: "Управление пользователями",
  MoveMembers: "Подвинуть пользователя",
  MuteMembers: "Замутить пользователя",
  PrioritySpeaker: "Приоретет микрофона",
  ReadMessageHistory: "Читать Историю Сообщений",
  RequestToSpeak: "Право на Разговор",
  SendMessages: "Отправлять сообщения",
  SendMessagesInThreads: "Отправлять сообщения в ветки",
  SendTTSMessages: "Отправлять ТТС Сообщения",
  Speak: "Говорить",
  Stream: "Стримить",
  UseApplicationCommands: "Использовать Команды приложений",
  UseEmbeddedActivities: "Использовать Ембед Активности",
  UseExternalEmojis: "Использовать внешние Емодзи",
  UseExternalStickers: "Использовать внешние Стикеры",
  UseVAD: "Использовать голосовую активность",
  ViewAuditLog: "Читать Лог Аудита",
  ViewChannel: "Просматривать канал",
  ViewGuildInsights: "Просмотр информации о сервере",
};
